#458: Commit message validation
dgroup/lazylead pull request #459
Opened 2021-08-17 19:47 UTC by VikNik599

2021-08-18 20:26 UTC, dgroup requested changes
Не уверен что на windows такая rake тачка будет работать. Подтверди плиз что работает или сделай копирование файлов силами Ruby, ибо sh выглядит как OS ориентировано…

2021-08-19 20:15 UTC, VikNik599 commented
> Не уверен что на windows такая rake таска будет работать. Подтверди плиз что работает или сделай копирование файлов силами Ruby, ибо sh выглядит как OS ориентировано…

Заводить руби на windows то еще удовольствие, конечно...
Но да, ты был прав, на windows такой подход не работает. Заюзал FileUtils. С ним отрабатывает. С sh в ошибку уходило.
![telegram-cloud-photo-size-2-5258098461155374316-y](https://user-images.githubusercontent.com/43455618/130137643-d2387f39-c298-478f-9073-de4d8db922f3.jpg)

2021-08-19 21:55 UTC, dgroup approved these changes

2021-08-19 21:56 UTC, dgroup commented
@rultor merge

2021-08-20 17:36 UTC, dgroup commented
@rultor

2021-08-20 17:36 UTC, dgroup commented
@rultor merge

2021-08-20 17:37 UTC, rultor commented
> @rultor merge 

@dgroup OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24937-902275770)

2021-08-20 17:41 UTC, merged

2021-08-20 17:41 UTC, rultor commented
> @rultor merge 

@dgroup Done! FYI, the full log is [here](https://www.rultor.com/t/24937-902275770) (took me 4min)

2021-08-20 17:44 UTC, rultor commented
> @rultor merge

@viknik599 @dgroup The pull request is closed already, so I can't merge it

2021-08-20 17:44 UTC, rultor commented
> @rultor merge

@dgroup I'm sorry, I don't understand you :( Check [this page](http://doc.rultor.com/basics.html) and try again please